# Site-wide settings
url: "https://heisenbergspizza.github.io"
baseurl: ""
title: "Zhou's Blog"
author:
  name: "HeisenbergsPizza"
  email: "Eidos_official@outlook.com"

# Build settings
theme: minima

# 保留 GitHub Pages 支持的插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# kramdown + MathJax
markdown: kramdown
kramdown:
  # input: GFM
  math_engine: mathjax
  math_engine_opts: {}

# Minima-specific settings
minima:
  skin: solarized-dark
  nav_pages:
    - about.md
  show_excerpts: false
  date_format: "%b %d, %Y"
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/HeisenbergsPizza"
  hide_site_feed_link: false
